### ISSUE TITLE
Requested package

### ISSUE THREAD

**Issue by pl-marasco** [xavi-rp/ResampleTool_notebook#5]
As in some case (Anaconda), not all the package are installed by default. May be would be useful to have an explicit file were declare all the package needed or check before the presence of the requested modules. 

In my version these modules were missing:
- raster
- netcdf 
- knitr (automatically download)

**Comment by xavi-rp** [comment]
Now 'raster' is self-installed, as 'knitr'.  I don't see anywhere using 'netcdf'

**Comment by pl-marasco** [comment]
If you try to open a dataset in NC format the module is requested. Maybe this option isn't contemplated but in my opinion would be a plus.

**Comment by xavi-rp** [comment]
Maybe it's a dependency of 'raster'... but then it should be there when installing 'raster'... Anyway, now it's self-installed as well

**Comment by PhenoloBoy** [comment]
For my understanding is needed if users try to read from NetCDF. In any case thanks

**Comment by pl-marasco** [comment]
For my understanding is needed if users try to read from NetCDF. In any case thanks
